### ISSUE TITLE
Links in the blog posts are broken

### ISSUE THREAD

**Issue by pratikmallya** [rackerlabs/docs-developer-blog#102]
e.g. https://developer.rackspace.com/blog/using-openstack-dns-for-domain-name-resolution/ is horribly broken.

Suggested solution: can we send out an email to all the authors asking them to review their contributions?

**Comment by catlook** [comment]
Tim says we should just delete the article all together.  I'll find out how to do that!

**Comment by catlook** [comment]
closed with https://github.com/rackerlabs/docs-developer-blog/pull/225
