### ISSUE TITLE
Add "AWS" category

### ISSUE THREAD

**Issue by djrut** [rackerlabs/docs-developer-blog#128]
Is there any chance we can add "AWS" to the Category section?

**Comment by ktbartholomew** [comment]
The only two posts that would be in this category are the two you recently authored, so probably not. Once there's at least a full page's worth of posts in this category we can consider it.

**Comment by ktbartholomew** [comment]
@djrut FWIW, Jekyll automatically generates pages for every category, so you could still see/share a link to this page: https://developer.rackspace.com/blog/categories/aws/.
