### ISSUE TITLE
comments: false is broken

### ISSUE THREAD

**Issue by everett-toews** [rackerlabs/docs-developer-blog#152]
For example

https://github.com/rackerlabs/docs-developer-blog/blob/master/_posts/2015-12-15-a-tutorial-on-application-development-using-vagrant-with-the-pycharm-ide.md

sets `comments: false` but the comments section appears in 

https://developer.rackspace.com/blog/a-tutorial-on-application-development-using-vagrant-with-the-pycharm-ide/

**Comment by catlook** [comment]
This may be an issue with Jekyll templates, if anyone is inspired to investigate.  This one may never be fixed as it is not critical.  Sorry :/

**Comment by catlook** [comment]
closing.
