### ISSUE TITLE
Language links broken

### ISSUE THREAD

**Issue by everett-toews** [rackerlabs/docs-developer-blog#158]
Go to https://developer.rackspace.com/sdks/golang/

Click Cloud Load Balancers (takes you to https://developer.rackspace.com/docs/cloud-load-balancers/getting-started/?lang=go)

Clicking on any of the languages in the "I’M CODING IN:" menu bar just leaves you on Go CLB page.

**Comment by annegentle** [comment]
What I see today when clicking through is that the ?lang=go link takes you to the curl examples, and then when I click on the Go menu bar option I do get gophercloud examples.

**Comment by carolynvs** [comment]
I don't think `?lang=X` works at all anymore, or at least I can't get any incantation of it to work. 😄  It would be nice to get functionality back so that we can provide direct links to customers instead of a link plus instructions to select a language.

**Comment by ktbartholomew** [comment]
@carolynvs has the correct diagnosis. The query string parameter is not being evaluated when setting the preferred language. If a user has chosen a language by clicking one of the little lang buttons, that will be used regardless of the query string provided. If they've never chosen a language, cURL is the default.
