### ISSUE TITLE
Provide a link to open an issue for unimplemented features

### ISSUE THREAD

**Issue by everett-toews** [rackerlabs/docs-developer-blog#159]
1 At the top of every language landing page there should be a link to creating a new issue here. 

e.g. https://developer.rackspace.com/sdks/golang/

"Support for additional services is on-going. To request support for a service, please [file an issue](https://github.com/rackerlabs/docs-developer-blog/issues/new) with the specific details."

2 Every place that reads "Not currently supported by this SDK" should have a link to creating a new issue here. 

e.g. https://developer.rackspace.com/docs/cloud-monitoring/getting-started/?lang=php

Under each code block where it reads "Not currently supported by this SDK" have text like "To request support for this feature, please [file an issue](https://github.com/rackerlabs/docs-developer-blog/issues/new) with the specific details."

**Comment by catlook** [comment]
Brilliant idea, but we have no resources to make any improvements to the landing pages.  There is at least an email link prominently displayed at the top of the pages.  If that account (sdk-support) gets enough inquiries of this nature, this idea may get traction.  We can open a new issue at that time.
