### ISSUE TITLE
OpenStack from source - content review

### ISSUE THREAD

**Issue by annegentle** [rackerlabs/docs-developer-blog#185]
Reported via email and let original author @phil-hopkins-a know:

I'm porting openstack from source into my environment, follows
https://developer.rackspace.com/blog/install-openstack-from-source/

I found the script in "Create the various users and directories needed for
the OpenStack services." has some error as follow:

1. miss "done" at the end of this script.
2. we have to run this script using "bash", not "sh".

**Comment by catlook** [comment]
https://github.com/rackerlabs/docs-developer-blog/pull/228
