### ISSUE TITLE
Custom Docker build environment

### ISSUE THREAD

**Issue by smashwilson** [rackerlabs/docs-developer-blog#190]
Because [jekyll-audit is an npm module](https://github.com/rackerlabs/docs-developer-blog/blob/master/.travis.yml#L15) instead of a Jekyll plugin, we can't use the standard quay.io/deconst/preparer-jekyll container to prepare this repository.

Instead, I'll have to:

- [x] Build a special container that includes both Ruby and Node, then the Jekyll preparer and jekyll-audit.
- [x] Whitelist the container in Nexus.
- [x] Designate it explicitly in `_deconst.json`.

**Comment by ktbartholomew** [comment]
Is it possible to have multiple builds (and thus multiple images) for a single repo?

**Comment by smashwilson** [comment]
Nope.

I have a general goal of revisiting the way that preparation is done to make it possible to have different containers do the initial "preparation" to JSON files on disk, then a pipeline of 0...n validation steps, then a final container to publish to the API (preferably in one HTTP upload). The jekyll-audit script could be introduced then as a pipeline container (presumably it'll have access to both the prepared JSON files and the original source).

I'm not sure how soon I'll be able to get to that, though; this is the fastest way to support jekyll-audit before then.

**Comment by smashwilson** [comment]
This now exists at [smashwilson/preparer-devblog](https://github.com/smashwilson/preparer-devblog). It was _super_ easy because Jekyll 2 already needed node to be installed :wink:

Remaining work:

- [ ] Whitelist `quay.io/smashwilson/preparer-devblog` on the Nexus build environment.
- [ ] Set the `preparer` key in the `_deconst.json` file.
- [ ] There is no step 3
