### ISSUE TITLE
Create a categories page

### ISSUE THREAD

**Issue by everett-toews** [rackerlabs/docs-developer-blog#193]
Create a categories page at https://developer.rackspace.com/blog/categories/

Then we could point blog authors there and ask them to pick a category from that or ask us to create a new category if there are enough posts for it.

**Comment by catlook** [comment]
I don't believe this will be fixed.  As Ash explained it to me, once there are enough articles for a new category, it is automatically added.  What's still missing is a way to see current, valid categories, but no resources are available to work on this.
