### ISSUE TITLE
Update pyrax SDK info with info about scheduled deprectation

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-developer-blog#218]
Hello Cat,

Again I'm reaching out to you directly to check where to direct my question, apologies for that.
Recently I advised customer to use Pyrax and linked him to our SDK Getting Started page.
After that I was notified that Pyrax will be getting decommissioned in favour of OpenStack SDK. This information is mentioned on Pyrax github but is nowhere present in our SDK documentation.
https://developer.rackspace.com/sdks/python/
This page says that official Rackspace SDK is Pyrax, yet on here it says in disclaimer that it will be decomed:
https://github.com/rackspace/pyrax/

Who could include or ammend the information on the SDKs page? It would be good to inform our customers of this projected change.

Thanks,
Jan 

Also update the [SDK Quickstart Guide python examples](https://github.com/rackerlabs/docs-quickstart) as needed.

**Comment by catlook** [comment]
Emailed Ken and Brian to get decomm dates and advice on whether this is worth pursuing.

**Comment by briancurtin** [comment]
No dates, but if you point me to wherever it is that disclaimer exists I'll provide alternate text.

**Comment by catlook** [comment]
@briancurtin This doc has no disclaimer and could s=use one: https://developer.rackspace.com/sdks/python/

I'm tracking down thge existing disclaimer as we speak.

**Comment by meker12** [comment]
Person's name is Jan Pokrzywinski <Jan.Pokrzywinski@rackspace.co.uk>.

**Comment by catlook** [comment]
You freaking rock!!!

-- Cat Lookabaugh, Sr. Information Developer
Rackspace Hosting – the #1 Managed Cloud Company
Info Dev Team      cat.lookabaugh@rackspace.com
Office: (210) 312-8193   Cell: (210) 364-1060

**Comment by catlook** [comment]
Brian,

Here is Jan’s response about current disclaimer.  Can you propose alternate text, or is it good?  Either way, I plan to add it to the Getting Started Pyrax guide, so let me know, please!

The place where I found info of pyrax being deprecated is it's official public github repo:
https://github.com/rackspace/pyrax

It mentions it in the second paragraph in the bold note. It states:

"""
Note: Please submit an issue before submitting a pull request so we can determine whether or not the change may be accepted. Pyrax is in the process of being deprecated in favor of the OpenStack SDK. We will announce the process and timelines for this deprecation as soon as we can.

-- Cat Lookabaugh, Sr. Information Developer
Rackspace Hosting – the #1 Managed Cloud Company
Info Dev Team      cat.lookabaugh@rackspace.com
Office: (210) 312-8193   Cell: (210) 364-1060

**Comment by briancurtin** [comment]
where

**Comment by catlook** [comment]
https://github.com/rackspace/pyrax/blob/master/README.rst

-- Cat Lookabaugh, Sr. Information Developer
Rackspace Hosting – the #1 Managed Cloud Company
Info Dev Team      cat.lookabaugh@rackspace.com
Office: (210) 312-8193   Cell: (210) 364-1060

**Comment by briancurtin** [comment]
Yeah, I wrote that one. Where else does something like that need to go?

**Comment by catlook** [comment]
In the intro to teh pyrax getting started guide.  Do you have more details about the timing?  I know we won't commit to a date.  But this year?  next year?  Is it imminent or just some time?  Anything to add about the implications?

**Comment by briancurtin** [comment]
I'm really just asking you what or where "pyrax getting started guide" is so I can make a change. No to everything else.

**Comment by catlook** [comment]
How about here: https://developer.rackspace.com/sdks/python/, right before the Requirements section?  Just scroll down a bit and you should see the text begin with the following:

Requirements
Using pyrax requires Python 2.7.x. There are plans to port it to run in both 2.x and 3.x, but that work has not yet been started. We recommend installing pip<https://pip.pypa.io/en/latest/installing.html> to handle all of the dependency requirements for pyrax.
Installation
Generally, pyrax should be installed into a virtual environment<http://docs.python-guide.org/en/latest/dev/virtualenvs/> using pip:


-- Cat Lookabaugh, Sr. Information Developer
Rackspace Hosting – the #1 Managed Cloud Company
Info Dev Team      cat.lookabaugh@rackspace.com
Office: (210) 312-8193   Cell: (210) 364-1060

**Comment by catlook** [comment]
Ok, it's added: https://staging.developer.rackspace.com/build-e52a694f73/sdks/python/ and will be published soon.  There is no additional information or time frame at this time.

**Comment by catlook** [comment]
https://github.com/rackerlabs/docs-developer-blog/pull/227
