### ISSUE TITLE
Header layout issues

### ISSUE THREAD

**Issue by rgbkrk** [rackerlabs/docs-developer-blog#5]
Width > 992 px:

![screenshot 2015-05-28 21 00 49](https://cloud.githubusercontent.com/assets/836375/7874970/81777ec0-057c-11e5-9a0f-ad55c2da3dbb.png)

:+1: 

Width of 992 px:

![screenshot 2015-05-28 20 58 50](https://cloud.githubusercontent.com/assets/836375/7874949/56a5f0be-057c-11e5-8005-54ed48b86bfd.png)

:+1: 

Width < 992 px:

![screenshot 2015-05-28 21 00 17](https://cloud.githubusercontent.com/assets/836375/7874964/737589b6-057c-11e5-9d73-661b4710ffcd.png)

:-1:

**Comment by smashwilson** [comment]
Does this also happen on https://developer.rackspace.com/ production, or is it a regression?

**Comment by smashwilson** [comment]
Ah - yes it does.
