### ISSUE TITLE
Add SEO metadata to pages and posts

### ISSUE THREAD

**Issue by ktbartholomew** [rackerlabs/docs-developer-blog#59]
(Depends on https://github.com/rackerlabs/nexus-control/issues/66)
- We should add variables to the frontmatter for all of the various meta tags. Back-filling some recent or high-traffic posts might be worthwhile.
- We should update [CONTRIBUTING.md](https://github.com/rackerlabs/docs-developer-blog/blob/master/CONTRIBUTING.md) to ask that post authors provide this information when they submit a new post.
- We (or Travis, or a mix of both) should evaluate contributor-provided metadata for length and keyword density.

**Comment by catlook** [comment]
Looks like https://github.com/rackerlabs/nexus-control/issues/66 was completed.  So where does that leave this issue?  Is it worth hanging on to. because someone cares and has time to address?  Or is it truly a "won't fix" and I should close it?  Or, is it actually already done? @smashwilson and @ktbartholomew ?

**Comment by ktbartholomew** [comment]
This issue is more about getting blog contributors to also write and include SEO metadata for their posts. https://github.com/rackerlabs/nexus-control/issues/66 set up the basic platform to make this possible, but the work here has not been done.

I wouldn't call it a "won't fix" though, we might get to it in the future. You know how priorities go 😃

**Comment by michaelmoussa** [comment]
Addressed / mostly addressed via #442 and rackerlabs/nexus-control#956. The `nexus-control` PR should have the side effect of automatically back-filling the meta/og tags on prior posts with better content rather than defaulting to the parent index page's meta content.

**Comment by catlook** [comment]
Closing now.  thanks, all.
