### ISSUE TITLE
category links are broken

### ISSUE THREAD

**Issue by steveortiz** [rackerlabs/docs-developer-blog#82]
Some of the category links appear to be broken.

web development - https://developer.rackspace.com/blog/categories/web%20development
data science - https://developer.rackspace.com/blog/categories/data%20science
rackspace.net - https://developer.rackspace.com/blog/categories/rackspace.net

**Comment by catlook** [comment]
@steveortiz Before you leave us for good...can you tell me where you found these categories and what they point to?

**Comment by steveortiz** [comment]
@catlook It appears this has been fixed and is no longer an issue. Multi-word categories like `security groups` [here](https://developer.rackspace.com/blog/Using-PowerShell-to-manage-Rackspace-Cloud-Security-Groups/) would result in broken category links. Now they appear to be hyphenated. I don't see the rackspace.net category any more either, so I'm going to assume that is no longer an issue either.

If you want to be extra thorough, you could run a link checker on the site... something to crawl through all the links on every page and identify broken links. If there are any more weird exceptions out there regarding category names being converted to links... that should turn them up.

**Comment by catlook** [comment]
Thanks, Steve!
